apiVersion: v1
kind: Service
metadata:
  annotations:
    enzo: "true"
  labels:
    app: cong-nextjs
    app.kubernetes.io/instance: cong-nextjs
    app.kubernetes.io/name: cong-nextjs
  name: cong-nextjs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: cong-nextjs
    app.kubernetes.io/name: cong-nextjs
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/rampadc/cong-nextjs
    enzo: "true"
  labels:
    app: cong-nextjs
    app.kubernetes.io/instance: cong-nextjs
    app.kubernetes.io/name: cong-nextjs
    app.openshift.io/runtime: js
  name: cong-nextjs
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: cong-nextjs
      app.kubernetes.io/name: cong-nextjs
  template:
    metadata:
      annotations:
        enzo: "true"
      labels:
        app.kubernetes.io/instance: cong-nextjs
        app.kubernetes.io/name: cong-nextjs
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: image-registry.openshift-image-registry.svc:5000/cong-nguyen-pipeline-from-scratch/cong-nextjs:39b7f49b326dc6ada7e95cf7faeec8eb2c0f3922
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cong-nextjs
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    enzo: "true"
    openshift.io/host.generated: "true"
  name: cong-nextjs
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: cong-nextjs
    weight: 100
  wildcardPolicy: None
